# Autogenerated by devscripts/update-version.py

__version__ = '2026.05.30.2'

RELEASE_GIT_HEAD = 'acf8ab7a6e3024325f62426e35a17f365c4d5d54'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'local'

_pkg_version = '2026.05.30.2'
